import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

/**
 * Multi-output build configuration
 * 
 * This configuration demonstrates how to build multiple JavaScript files
 * from different TypeScript entry points.
 * 
 * Outputs:
 * - dist/main.js (main plugin)
 * - dist/advanced.js (advanced features module)
 * 
 * To use this config instead of esbuild.config.mjs:
 * 1. Update package.json scripts to use this file
 * 2. Update manifest.json if needed
 * 3. Copy both JS files to Obsidian plugin directory
 */
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [
		{ in: "src/main.ts", out: "main" },
		{ in: "src/advanced/advancedFeatures.ts", out: "advanced" }
	],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "dist",  // Output directory for multiple files
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
